### PR TITLE
Review for cryo

### PR DESCRIPTION
**Pull request by dilanbhalla**
Security review for cryo, an npm package.

### CODE REVIEW

**Comment by dilanbhalla** [comment]
Also, I just noticed the GitHub issue regarding the definition of "security reviews," and that reviews relating to trusted third party security audits, thread models, etc are preferred over known, coordinated disclosures. I'll make that my focus for future reviews!

**Comment by scovetta** [comment]
@dilanbhalla I'm not sure that we settled on the issue of external vs. "done by the submitter" -- I'd prefer we have both, but take a look at #25 and https://github.com/nodejs/security-wg -- maybe there's a useful way to integrate the whole Node security advisory database via a single script.

**Comment by dilanbhalla** [comment]
@scovetta sounds great. I'll take a look at the Node security advisory database and see if I can integrate them with a script.

**Comment by jenniferfernick** [comment]
> Also, I just noticed the GitHub issue regarding the definition of "security reviews," and that reviews relating to trusted third party security audits, thread models, etc are preferred over known, coordinated disclosures. I'll make that my focus for future reviews!

To be clear on this, I believe the reasoning here is that security reviews, while often not full-scope, tend to be scoped to get a strong feel for the security of a specific section of the codebase, often the most security-critical parts. Posting individual advisories from coordinated disclosures is less illustrative because it lacks the broader context that a review/audit might demonstrate. Advisories are still super valuable, but probably not the fit for the intention of this repo, would you agree @scovetta?

**Comment by scovetta** [comment]
@jenniferfernick I think I could be convinced either way -- how about we tee this up for discussion at the next WG meeting?

**Pull request merged**
