### PR TITLE
Update template to add version or commit ID

### PR DESCRIPTION
**Pull request by dcmiddle**
Be clear on what version of the code was reviewed. This can be done
either by the version string of a release build, a release tag in the
source repository, or failing that a raw commit-ID from head commit at
the time the code was reviewed.

### CODE REVIEW

**Comment by scovetta** [comment]
Thanks @dcmiddle! 

Some thoughts:

* Most package managers (all?) have immutable versions, so `pkg:npm/foo@1.2.3` shouldn't ever change meaning, and don't necessarily reference a source repository at all.
* For GitHub (and other source repos), the [PackageURL spec](https://github.com/package-url/purl-spec) supports commits and tags, like `pkg:github/package-url/purl-spec@244fd47e07d1004f0aed9c`. 
* There's a fallback, `generic` PackageURL type that can be used when needed, like `pkg:generic/openssl@1.1.10g?download_url=https://openssl.org/source/openssl-1.1.0g.tar.gz&checksum=sha256:de4d501267da`.

I agree that we don't want ambiguous references -- so `pkg:github/foo/bar` should be rejected without a commit or tag. We can add this logic to the validator.

**Comment by dcmiddle** [comment]
I see... I wasn't sure if `package` was being used in exactly that way or as a generic reference to the project artifact that was reviewed.
In some cases projects aren't released as packages or for some other reason a source reference is more appropriate.
For example, often when I go to review a project, I won't necessarily first audit an artifact but instead check out their repo. See what the source looks like, what their commit discipline is like, maintainer diversity, etc.

With that in mind, I could change `package-version` to something like `source-version`?
I could also add `source-url` as a separate field.

**Comment by scovetta** [comment]
I *think* we can keep the PacakgeURL field, and use it to reference the source URL -- e.g.:

```
Package-URLs:
- pkg:github/madler/zlib@cacf7f1d4e3d44d871b605da3b647f07d718623f
```
This should cover the `git clone` case. If the source isn't hosted on GitHub (let's say, an archive file on a "random" website), then you can use the `generic` type:

```
Package-URLs:
- pkg:generic/monkeys-audio@570?download_url=https://monkeysaudio.com/files/MAC_SDK_570.zip&checksum=sha256:abcdef123456
```

Would that cover all bases?

**Comment by dcmiddle** [comment]
Is it your goal to keep this machine readable so there's possible integration with package feeds etc?
If so then it makes more sense to drop this commit and stick with what you have.

**Comment by scovetta** [comment]
Thanks @dcmiddle! Yeah, I think the metadata should be machine parse-able, so if you don't mind, I'll close this PR and if we need to adjust the package url area to account for edge cases, we can certainly do that. Thanks for your input!!

**Pull request closed without merging**
